services:
  ansible:
    image: chrisengelhard/ansible-docker-utility:slim-2.18.6
    container_name: chrisengelhard/ansible-docker-utility
    environment:
      - TZ=${TZ:-Europe/Amsterdam}
    volumes:
      - .:/ansible
    working_dir: /ansible
    # Keep the container running
    command: tail -f /dev/null
